### ISSUE TITLE
Two Icons on Android

### ISSUE THREAD

**Issue by blimkemann** [adamfisher/Xamarin.Forms.VideoPlayer#88]
I have an app deployed that includes this player and when it is installed TWO icons appear. One is correct, shows my app's icon and name. The SECOND shows my app's icon but has the name Octane.Xamarin.Forms.VideoPlayer I am using 2.0.0 and I did not see this in older versions.

**Comment by khuongntrd** [comment]
The integration with Xamarin Forms is working, video play well but app installed in android device with 2 launcher icons, one with my app name and one with "Octane.Xamarin.Forms.VideoPlayer". I'm check compiled AndroidManifest.xml file and got additional activity like this:
`<activity android:configChanges="orientation|screenSize" android:icon="@drawable/icon" android:label="Octane.Xamarin.Forms.VideoPlayer" android:name="md5ae95e19a8a406422c07caec4fc239b30.MainActivity"> <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity>`

**Comment by adamfisher** [comment]
If you recently changed your bundle identifier inside the `AndroidManifest.xml` you will get two app launcher icons. I would check that first.

**Comment by blimkemann** [comment]
My bundle identifier is definitely the same. And, this didn’t happen until I upgraded to version 2.0.0

**Comment by JMNewsome** [comment]
I have this issue two and it only began when using 2.0.0, I haven't changed anything in the AndroiManifest recently

**Comment by adamfisher** [comment]
This should be fixed with version 2.1.0 available on NuGet.org.

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/releases/tag/2.1.0

**Comment by blimkemann** [comment]
Thank you!

**Comment by ryanherman** [comment]
@adamfisher I am running Octane.Xam.VideoPlayer from Nuget version 2.1.0 and I am still getting double icons.  The app is on the Google Play - 1iota

Let me know what I should do please.
